---
abstract: 'NGS::Tools::Picard Perl package for Picard suite of tools'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NGS-Tools-Picard
provides:
  NGS::Tools::Picard:
    file: lib/NGS/Tools/Picard.pm
    version: '0.17'
  NGS::Tools::Picard::AddOrReplaceReadGroups:
    file: lib/NGS/Tools/Picard/AddOrReplaceReadGroups.pm
  NGS::Tools::Picard::CollectInsertSizeMetrics:
    file: lib/NGS/Tools/Picard/CollectInsertSizeMetrics.pm
  NGS::Tools::Picard::CollectMultipleMetrics:
    file: lib/NGS/Tools/Picard/CollectMultipleMetrics.pm
  NGS::Tools::Picard::MarkDuplicates:
    file: lib/NGS/Tools/Picard/MarkDuplicates.pm
  NGS::Tools::Picard::MergeSamFiles:
    file: lib/NGS/Tools/Picard/MergeSamFiles.pm
  NGS::Tools::Picard::MetricsParser:
    file: lib/NGS/Tools/Picard/MetricsParser.pm
  NGS::Tools::Picard::ReplaceSamHeader:
    file: lib/NGS/Tools/Picard/ReplaceSamHeader.pm
  NGS::Tools::Picard::Roles::Core:
    file: lib/NGS/Tools/Picard/Roles/Core.pm
  NGS::Tools::Picard::SamToFastq:
    file: lib/NGS/Tools/Picard/SamToFastq.pm
  NGS::Tools::Picard::SortSam:
    file: lib/NGS/Tools/Picard/SortSam.pm
  NGS::Tools::Picard::ValidateSamFile:
    file: lib/NGS/Tools/Picard/ValidateSamFile.pm
requires:
  Carp: '0'
  Moose: '0'
  Moose::Role: '0'
version: '0.17'
