package NGS::Tools::Picard::SamToFastq;
use Moose::Role;
use MooseX::Params::Validate;

with 'NGS::Tools::Picard::Roles::Core';

use strict;
use warnings FATAL => 'all';
use namespace::autoclean;
use autodie;
use Carp;
use File::Path qw(make_path);

=head1 NAME

NGS::Tools::Picard::SamToFastq

=head1 SYNOPSIS

A Perl Moose Role for Picard's SamToFastq.jar file.

=head1 ATTRIBUTES AND DELEGATES

=head1 SUBROUTINES/METHODS

=head2 $obj->SamToFastq()

Converts a SAM/BAM file to a FASTQ.

=head3 Arguments:

=over 2

=item * input: SAM/BAM file for processing.

=item * type: single or paired (default: paired)

=item * readgroup: true/false to determine whether to output FASTQ files per read group (optional, default: true)

=item * stringency: validation stringency (default: LENIENT)

=item * java: full path to the Java program (default: java)

=item * picard: full path to the directory containing the Picard suite of tools (default: $PICARDROOT)

=item * memory: memory to allocate to the Java program in gigabytes(default: 4)

=item * tmpdir: name of temporary directory to store temp files generated by Picard (default: none)

=back

=cut

sub SamToFastq {
	my $self = shift;
	my %args = validated_hash(
		\@_,
		input => {
			isa         => 'Str',
			required    => 1
			},
		type => {
			isa			=> 'Str',
			required	=> 0,
			default		=> 'paired'
			},
		readgroup => {
			isa			=> 'Str',
			required	=> 0,
			default		=> 'false'
			},
		stringency => {
			isa			=> 'Str',
			required	=> 0,
			default		=> $self->get_validation_stringency()
			},
		java => {
			isa			=> 'Str',
			required	=> 0,
			default		=> $self->get_java()
			},
		picard => {
			isa			=> 'Str',
			required	=> 0,
			default		=> $self->get_picard()
			},
		memory => {
			isa			=> 'Int',
			required	=> 0,
			default		=> 4
			},
		tmpdir => {
			isa			=> 'Str',
			required	=> 0,
			default		=> $self->get_tmpdir()
			}
		);

	my $read1;
	my $read2;
	my $second_end_fastq;
	if ($args{'type'} eq 'paired') {
		$read1 = join('.',
			join('_', File::Basename::basename($args{'input'}, qw( .sam .bam )), '_R1'),
			'fastq',
			'gz'
			);
		$read2 = join('.',
			join('_', File::Basename::basename($args{'input'}, qw( .sam .bam )), '_R2'),
			'read2',
			'fastq',
			'gz'
			);
		$second_end_fastq = join('',
			'SECOND_END_FASTQ=',
			$read2
			);
		}
	elsif ($args{'type'} eq 'single') {
		$read1 = join('.',
			File::Basename::basename($args{'input'}, qw( .sam .bam )),
			'read1',
			'fastq',
			'gz'
			);
		}
	else {
		croak("Invalid type, must be either paired or single\n");
		}
	my $memory = join('',
		$args{'memory'},
		'g'
		);

	my $picard_jar = join('/',
		$args{'picard'},
		'SamToFastq.jar'
		);
	my $program = join(' ',
		$args{'java'},
		'-Xmx' . $memory,
		);
	# create a tmpdir and use it in the java command
	if ($args{'tmpdir'} ne '') {
		$program = join(' ',
			$program,
			'-Djava.io.tmpdir=' . $args{'tmpdir'}
			);
		}
    $program = join(' ',
    	$program,
    	'-jar',
    	$picard_jar
    	);
    my $options = join(' ',
    	'INPUT=' . $args{'input'},
    	'VALIDATION_STRINGENCY=' . $args{'stringency'},
    	'INCLUDE_NON_PF_READS=' . 'true'
    	);
	if ($args{'readgroup'} eq 'true') {
		$options = join(' ',
			$options,
			'OUTPUT_PER_RG=' . $args{'readgroup'}
			);
		}
	elsif ($args{'readgroup'} eq 'false') {
		if ($args{'type'} ne 'paired') {
			$options = join(' ',
				$options,
				'FASTQ=' . $read1
				);
			}
		elsif ($args{'type'} eq 'true') {
			$options = join(' ',
				$options,
				'FASTQ=' . $read1,
				$second_end_fastq
				);
			}
		}
	# $options = join(' ',
	# 	'INPUT=' . $args{'input'},
	# 	'FASTQ=' . $read1,
	# 	'VALIDATION_STRINGENCY=' . $args{'stringency'},
	# 	'INCLUDE_NON_PF_READS=' . 'true'
	# 	);

	# if ($args{'type'} eq 'paired') {
	# 	$options = join(' ',
	# 		$options,
	# 		$second_end_fastq
	# 		);
	# 	}

	my $cmd = join(' ',
		$program,
		$options
		);

	my %return_values = (
		cmd => $cmd,
		read1 => $read1,
		read2 => $read2
		);

	return(\%return_values);
	}

=head1 AUTHOR

Richard de Borja, C<< <richard.deborja at sickkids.ca> >>

=head1 ACKNOWLEDGEMENT

Dr. Adam Shlien, PI -- The Hospital for Sick Children

=head1 BUGS

Please report any bugs or feature requests to C<bug-test-test at rt.cpan.org>, or through
the web interface at L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=test-test>.  I will be notified, and then you'll
automatically be notified of progress on your bug as I make changes.

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc NGS::Tools::Picard::SamToFastq

You can also look for information at:

=over 4

=item * RT: CPAN's request tracker (report bugs here)

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=test-test>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/test-test>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/test-test>

=item * Search CPAN

L<http://search.cpan.org/dist/test-test/>

=back

=head1 ACKNOWLEDGEMENTS

=head1 LICENSE AND COPYRIGHT

Copyright 2013 Richard de Borja.

This program is free software; you can redistribute it and/or modify it
under the terms of the the Artistic License (2.0). You may obtain a
copy of the full license at:

L<http://www.perlfoundation.org/artistic_license_2_0>

Any use, modification, and distribution of the Standard or Modified
Versions is governed by this Artistic License. By using, modifying or
distributing the Package, you accept this license. Do not use, modify,
or distribute the Package, if you do not accept this license.

If your Modified Version has been derived from a Modified Version made
by someone other than you, you are nevertheless required to ensure that
your Modified Version complies with the requirements of this license.

This license does not grant you the right to use any trademark, service
mark, tradename, or logo of the Copyright Holder.

This license includes the non-exclusive, worldwide, free-of-charge
patent license to make, have made, use, offer to sell, sell, import and
otherwise transfer the Package with respect to any patent claims
licensable by the Copyright Holder that are necessarily infringed by the
Package. If you institute patent litigation (including a cross-claim or
counterclaim) against any party alleging that the Package constitutes
direct or contributory patent infringement, then this Artistic License
to you shall terminate on the date that such litigation is filed.

Disclaimer of Warranty: THE PACKAGE IS PROVIDED BY THE COPYRIGHT HOLDER
AND CONTRIBUTORS "AS IS' AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES.
THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, OR NON-INFRINGEMENT ARE DISCLAIMED TO THE EXTENT PERMITTED BY
YOUR LOCAL LAW. UNLESS REQUIRED BY LAW, NO COPYRIGHT HOLDER OR
CONTRIBUTOR WILL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THE PACKAGE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=cut

no Moose::Role;

1; # End of NGS::Tools::Picard::SamToFastq
